#include "html_ui_templates.h"

const char *HTML_UI_TEMPLATE_SCAN_HOME =
    "<card id=\"screen\" data-xp=\"0\" data-yp=\"0\" data-wp=\"100\" data-hp=\"100\""
    " data-bg-color-light=\"INFORMATION_BOX\" data-bg-color-dark=\"INFORMATION_BOX\">"
    "<card id=\"hero\" data-xp=\"5\" data-yp=\"6\" data-wp=\"90\" data-hp=\"30\""
    " data-bg-color-light=\"PRIMARY\" data-bg-color-dark=\"HEADER_BOX\""
    " data-border-color-light=\"INFORMATION_LINE\" data-border-color-dark=\"SUMMARY_LINE\">"
    "<icon id=\"hero_icon\" data-icon=\"GLOBE_SMALL\" data-xp=\"10\" data-yp=\"12\"></icon>"
    "<label id=\"title\" data-xp=\"35\" data-yp=\"16\" size=\"31\""
    " data-text-color-light=\"TEXT\" data-text-color-dark=\"TEST_COLOR_WHITE\">"
    "[[BUTTON_TEXT.ENTER_PIN_CODE]]"
    "</label>"
    "<label id=\"subtitle\" data-xp=\"35\" data-yp=\"20\" size=\"26\""
    " data-text-color-light=\"TEXT\" data-text-color-dark=\"TEST_COLOR_WHITE\">"
    "[[ENTER_CODE.l3]]"
    "</label>"
    "</card>"
    "<row id=\"row_demo\" data-xp=\"5\" data-yp=\"38\" data-wp=\"90\" data-hp=\"13\""
    " data-bg-color-light=\"PRIMARY\" data-bg-color-dark=\"HEADER_BOX\""
    " data-border-color-light=\"INFORMATION_LINE\" data-border-color-dark=\"SUMMARY_LINE\">"
    "<label id=\"row_title\" data-row-wp=\"25\" size=\"27\""
    " data-text-color-light=\"TEXT\" data-text-color-dark=\"TEST_COLOR_WHITE\">"
    "ROW"
    "</label>"
    "<label id=\"row_tv_1\" data-row-wp=\"25\" size=\"26\""
    " data-text-color-light=\"TEXT\" data-text-color-dark=\"TEST_COLOR_WHITE\">"
    "TV 1"
    "</label>"
    "<label id=\"row_tv_2\" data-row-wp=\"25\" size=\"26\""
    " data-text-color-light=\"TEXT\" data-text-color-dark=\"TEST_COLOR_WHITE\">"
    "TV 2"
    "</label>"
    "<label id=\"row_tv_3\" data-row-wp=\"25\" size=\"26\""
    " data-text-color-light=\"TEXT\" data-text-color-dark=\"TEST_COLOR_WHITE\">"
    "TV 3"
    "</label>"
    "</row>"
    "<column id=\"column_demo\" data-xp=\"5\" data-yp=\"54\" data-wp=\"90\" data-hp=\"13\""
    " data-bg-color-light=\"PRIMARY\" data-bg-color-dark=\"HEADER_BOX\""
    " data-border-color-light=\"INFORMATION_LINE\" data-border-color-dark=\"SUMMARY_LINE\">"
    "<label id=\"column_title\" data-column-hp=\"25\" size=\"27\""
    " data-text-color-light=\"TEXT\" data-text-color-dark=\"TEST_COLOR_WHITE\">"
    "COLUMN"
    "</label>"
    "<label id=\"column_tv_1\" data-column-hp=\"25\" size=\"26\""
    " data-text-color-light=\"TEXT\" data-text-color-dark=\"TEST_COLOR_WHITE\">"
    "TV 1"
    "</label>"
    "<label id=\"column_tv_2\" data-column-hp=\"25\" size=\"26\""
    " data-text-color-light=\"TEXT\" data-text-color-dark=\"TEST_COLOR_WHITE\">"
    "TV 2"
    "</label>"
    "<label id=\"column_tv_3\" data-column-hp=\"25\" size=\"26\""
    " data-text-color-light=\"TEXT\" data-text-color-dark=\"TEST_COLOR_WHITE\">"
    "TV 3"
    "</label>"
    "</column>"
    "<button id=\"lang\" data-yp=\"76\" data-wp=\"49\" data-hp=\"7.4\" data-gravity-x=\"left\" data-radius=\"6\""
    " data-action=\"language\" data-target-html-screen=\"1\" data-key=\"L\""
    " data-bg-color-light=\"PRIMARY\" data-bg-color-dark=\"TEST_COLOR_BLUE\""
    " data-text-color-light=\"TEST_COLOR_WHITE\" data-text-color-dark=\"TEST_COLOR_WHITE\""
    " data-border-color-light=\"TEST_COLOR_WHITE\" data-border-color-dark=\"TEST_COLOR_WHITE\">"
    "[[BUTTON_TEXT.CHANGE_LANGUAGE]]"
    "</button>"
    "<button id=\"mode\" data-yp=\"76\" data-wp=\"49\" data-hp=\"7.4\" data-gravity-x=\"right\" data-radius=\"6\""
    " data-action=\"mode\" data-target-html-screen=\"2\" data-key=\"R\""
    " data-bg-color-light=\"PRIMARY\" data-bg-color-dark=\"TEST_COLOR_RED\""
    " data-text-color-light=\"TEST_COLOR_WHITE\" data-text-color-dark=\"TEST_COLOR_WHITE\""
    " data-border-color-light=\"TEST_COLOR_WHITE\" data-border-color-dark=\"TEST_COLOR_WHITE\">"
    "[[BUTTON_TEXT.DARK_MODE]]"
    "</button>"
    "<button id=\"scan\" data-yp=\"86\" data-wp=\"49\" data-hp=\"7.4\" data-gravity-x=\"left\" data-radius=\"6\""
    " data-action=\"scan\" data-target-html-screen=\"3\" data-key=\"l\""
    " data-bg-color-light=\"PRIMARY\" data-bg-color-dark=\"TEST_COLOR_BLACK\""
    " data-text-color-light=\"TEST_COLOR_WHITE\" data-text-color-dark=\"TEST_COLOR_WHITE\""
    " data-border-color-light=\"TEST_COLOR_WHITE\" data-border-color-dark=\"TEST_COLOR_WHITE\">"
    "[[BUTTON_TEXT.SCAN_CODE]]"
    "</button>"
    "<button id=\"courier\" data-yp=\"86\" data-wp=\"49\" data-hp=\"7.4\" data-gravity-x=\"right\" data-radius=\"6\""
    " data-action=\"courier\" data-target-html-screen=\"4\" data-key=\"r\""
    " data-bg-color-light=\"PRIMARY\" data-bg-color-dark=\"TEST_COLOR_GREEN\""
    " data-text-color-light=\"TEST_COLOR_WHITE\" data-text-color-dark=\"TEST_COLOR_WHITE\""
    " data-border-color-light=\"TEST_COLOR_WHITE\" data-border-color-dark=\"TEST_COLOR_WHITE\">"
    "[[BUTTON_TEXT.COURIER]]"
    "</button>"
    "</card>";

const char *HTML_UI_TEMPLATE_DUMMY_LANGUAGE =
    "<card id=\"lang_screen\" data-xp=\"0\" data-yp=\"0\" data-wp=\"100\" data-hp=\"100\""
    " data-bg-color-light=\"INFORMATION_BOX\" data-bg-color-dark=\"INFORMATION_BOX\">"
    "<card id=\"lang_panel\" data-xp=\"6\" data-yp=\"10\" data-wp=\"88\" data-hp=\"30\""
    " data-bg-color-light=\"INFORMATION_BOX\" data-bg-color-dark=\"HEADER_BOX\">"
    "<label id=\"lang_title\" data-xp=\"35\" data-yp=\"18\" size=\"48\""
    " data-text-color-light=\"PRIMARY\" data-text-color-dark=\"TEST_COLOR_WHITE\">"
    "Language dummy screen"
    "</label>"
    "<label id=\"lang_note\" data-xp=\"35\" data-yp=\"24\" size=\"30\""
    " data-text-color-light=\"TEXT\" data-text-color-dark=\"TEST_COLOR_WHITE\">"
    "Triggered by Language action"
    "</label>"
    "<label id=\"lang_debug\" data-xp=\"35\" data-yp=\"30\" size=\"26\" data-text-color=\"DISABLE_TEXT\">"
    "DEBUG: screen=LANGUAGE_DUMMY"
    "</label>"
    "</card>"
    "<button id=\"lang_back\" data-xp=\"30\" data-yp=\"84\" data-wp=\"40\" data-hp=\"7.2\""
    " data-action=\"back_home\" data-target-html-screen=\"0\" data-key=\"L\""
    " data-bg-color-light=\"PRIMARY\" data-bg-color-dark=\"TEST_COLOR_BLACK\""
    " data-text-color-light=\"TEST_COLOR_WHITE\" data-text-color-dark=\"TEST_COLOR_WHITE\""
    " data-border-color-light=\"TEST_COLOR_WHITE\" data-border-color-dark=\"TEST_COLOR_WHITE\">"
    "[[BUTTON_TEXT.BACK]]"
    "</button>"
    "</card>";

const char *HTML_UI_TEMPLATE_DUMMY_MODE =
    "<card id=\"mode_screen\" data-xp=\"0\" data-yp=\"0\" data-wp=\"100\" data-hp=\"100\""
    " data-bg-color-light=\"INFORMATION_BOX\" data-bg-color-dark=\"INFORMATION_BOX\">"
    "<card id=\"mode_panel\" data-xp=\"6\" data-yp=\"10\" data-wp=\"88\" data-hp=\"30\""
    " data-bg-color-light=\"INFORMATION_BOX\" data-bg-color-dark=\"HEADER_BOX\">"
    "<label id=\"mode_title\" data-xp=\"35\" data-yp=\"18\" size=\"48\""
    " data-text-color-light=\"PRIMARY\" data-text-color-dark=\"TEST_COLOR_WHITE\">"
    "Mode dummy screen"
    "</label>"
    "<label id=\"mode_note\" data-xp=\"35\" data-yp=\"24\" size=\"30\""
    " data-text-color-light=\"TEXT\" data-text-color-dark=\"TEST_COLOR_WHITE\">"
    "Triggered by Dark/Light action"
    "</label>"
    "<label id=\"mode_debug\" data-xp=\"35\" data-yp=\"30\" size=\"26\" data-text-color=\"DISABLE_TEXT\">"
    "DEBUG: screen=MODE_DUMMY"
    "</label>"
    "</card>"
    "<button id=\"mode_back\" data-xp=\"30\" data-yp=\"84\" data-wp=\"40\" data-hp=\"7.2\""
    " data-action=\"back_home\" data-target-html-screen=\"0\" data-key=\"L\""
    " data-bg-color-light=\"PRIMARY\" data-bg-color-dark=\"TEST_COLOR_BLACK\""
    " data-text-color-light=\"TEST_COLOR_WHITE\" data-text-color-dark=\"TEST_COLOR_WHITE\""
    " data-border-color-light=\"TEST_COLOR_WHITE\" data-border-color-dark=\"TEST_COLOR_WHITE\">"
    "[[BUTTON_TEXT.BACK]]"
    "</button>"
    "</card>";

const char *HTML_UI_TEMPLATE_DUMMY_SCAN =
    "<card id=\"scan_screen\" data-xp=\"0\" data-yp=\"0\" data-wp=\"100\" data-hp=\"100\""
    " data-bg-color-light=\"INFORMATION_BOX\" data-bg-color-dark=\"INFORMATION_BOX\">"
    "<card id=\"scan_panel\" data-xp=\"6\" data-yp=\"10\" data-wp=\"88\" data-hp=\"30\""
    " data-bg-color-light=\"INFORMATION_BOX\" data-bg-color-dark=\"HEADER_BOX\">"
    "<label id=\"scan_title\" data-xp=\"35\" data-yp=\"18\" size=\"48\""
    " data-text-color-light=\"PRIMARY\" data-text-color-dark=\"TEST_COLOR_WHITE\">"
    "Scan dummy screen"
    "</label>"
    "<label id=\"scan_note\" data-xp=\"35\" data-yp=\"24\" size=\"30\""
    " data-text-color-light=\"TEXT\" data-text-color-dark=\"TEST_COLOR_WHITE\">"
    "Triggered by Scan action"
    "</label>"
    "<label id=\"scan_debug\" data-xp=\"35\" data-yp=\"30\" size=\"26\" data-text-color=\"DISABLE_TEXT\">"
    "DEBUG: screen=SCAN_DUMMY"
    "</label>"
    "</card>"
    "<button id=\"scan_back\" data-xp=\"30\" data-yp=\"84\" data-wp=\"40\" data-hp=\"7.2\""
    " data-action=\"back_home\" data-target-html-screen=\"0\" data-key=\"L\""
    " data-bg-color-light=\"PRIMARY\" data-bg-color-dark=\"TEST_COLOR_BLACK\""
    " data-text-color-light=\"TEST_COLOR_WHITE\" data-text-color-dark=\"TEST_COLOR_WHITE\""
    " data-border-color-light=\"TEST_COLOR_WHITE\" data-border-color-dark=\"TEST_COLOR_WHITE\">"
    "[[BUTTON_TEXT.BACK]]"
    "</button>"
    "</card>";

const char *HTML_UI_TEMPLATE_DUMMY_COURIER =
    "<card id=\"courier_screen\" data-xp=\"0\" data-yp=\"0\" data-wp=\"100\" data-hp=\"100\""
    " data-bg-color-light=\"INFORMATION_BOX\" data-bg-color-dark=\"INFORMATION_BOX\">"
    "<card id=\"courier_panel\" data-xp=\"6\" data-yp=\"10\" data-wp=\"88\" data-hp=\"30\""
    " data-bg-color-light=\"INFORMATION_BOX\" data-bg-color-dark=\"HEADER_BOX\">"
    "<label id=\"courier_title\" data-xp=\"35\" data-yp=\"18\" size=\"48\""
    " data-text-color-light=\"PRIMARY\" data-text-color-dark=\"TEST_COLOR_WHITE\">"
    "Courier dummy screen"
    "</label>"
    "<label id=\"courier_note\" data-xp=\"35\" data-yp=\"24\" size=\"30\""
    " data-text-color-light=\"TEXT\" data-text-color-dark=\"TEST_COLOR_WHITE\">"
    "Triggered by Courier action"
    "</label>"
    "<label id=\"courier_debug\" data-xp=\"35\" data-yp=\"30\" size=\"26\" data-text-color=\"DISABLE_TEXT\">"
    "DEBUG: screen=COURIER_DUMMY"
    "</label>"
    "</card>"
    "<button id=\"courier_back\" data-xp=\"30\" data-yp=\"84\" data-wp=\"40\" data-hp=\"7.2\""
    " data-action=\"back_home\" data-target-html-screen=\"0\" data-key=\"L\""
    " data-bg-color-light=\"PRIMARY\" data-bg-color-dark=\"TEST_COLOR_BLACK\""
    " data-text-color-light=\"TEST_COLOR_WHITE\" data-text-color-dark=\"TEST_COLOR_WHITE\""
    " data-border-color-light=\"TEST_COLOR_WHITE\" data-border-color-dark=\"TEST_COLOR_WHITE\">"
    "[[BUTTON_TEXT.BACK]]"
    "</button>"
    "</card>";
